### ISSUE TITLE
iOS: Migrate to Maplibre

### ISSUE THREAD

**Issue by m0nac0** [maplibre/flutter-maplibre-gl#2]
Currently, I've gotten the plugin to compile on iOS, but it still uses Mapbox GL Native, not Maplibre GL Native. 

I most likely won't be able to perform this migration, so any help/contributions are very welcome!

**Comment by thiphariel** [comment]
Hi @m0nac0 , I have all the setup to build on macOS, but i'm just not used to all of this and mapbox-gl in general. If you think you can guide a bit through, I can test some things for you.

Just tell me !

**Comment by m0nac0** [comment]
Amazing! I'll be happy to help as much as possible, but I don't know much about iOS development either 😂
 
You can take a look at the [m0-ios-extension branch](https://github.com/tobrun/flutter-mapbox-gl/compare/master...m0nac0:m0-ios-extension). (Most important commits are  0961470ca7c95399bed99a12dd079821efa41487 and 4e617e5bf87def84df1b218700a0fe4779eb171a)
I played around a little bit there, but without a Mac I always had to push and wait for the Github Actions build to fail and wasn't able to solve the error.

This plugin directly referenced the Mapbox iOS SDK, which I changed to use the Maplibre iOS SDK. But the plugin also referenced the Mapbox iOS Annotation extension, which in turn also references the Mapbox iOS SDK. So I forked the Annotation extension (https://github.com/m0nac0/maplibre-annotation-extension) and modified it to also use the Maplibre SDK. Then I modified this plugin to use my fork of the annotation extension.

But when I now try to compile the example app I get this error (because of the annotation extension):
```
flutter-maplibre-gl/flutter-maplibre-gl/example/ios/Pods/MaplibreAnnotationExtension/MapboxAnnotationExtension/Annotations/MGLStyleAnnotation.h:2:9: fatal error: module 'Mapbox' not found
    @import Mapbox;
```
If I replace `@import Mapbox` with `@import MapLibre` in my fork of the annotation extension I still get a similar error that module 'MapLibre' was not found.

So I think the best way to start would be opening both projects (this repo and the forked annotation extension) in Xcode and try:
- to compile the example app and see if Xcode provides more helpful error messages or tools
- try to edit the `@import Mapbox;` line in `MaplibreAnnotationExtension/MapboxAnnotationExtension/Annotations/MGLStyleAnnotation.h` in the forked annotation extension and see if Xcode helps you pick/autocomplete the right module name.

Let me know if you have more questions, I'm not sure how good my explanation was ;)

**Comment by thiphariel** [comment]
Oh, I didn't see your response...

I could try something on some off day, but I really don't know when I could try this ahah

I'll report here when I can watch it 😁

**Comment by mindthefish** [comment]
I was able to compile for iOS. Changes have to be made in maplibre-cocoapods, maplibre-annotation-extension and here in flutter-maplibre-gl. Due to dependant references it makes sense to apply changes one after the other. I opened https://github.com/m0nac0/maplibre-cocoapods/pull/1 for the cocoapods changes and https://github.com/m0nac0/maplibre-annotation-extension/pull/1 for annotation extension changes. These currently still link to my fork and should be changed after the cocoapods PR merge.

**Comment by mindthefish** [comment]
In order to run the updated flutter-maplibre-gl package, I had to merge your changes from the master @m0nac0. PR is open: https://github.com/m0nac0/flutter-maplibre-gl/pull/7

Also we have to update the Podfile in the example folder, once the PRs are merged.

**Comment by mindthefish** [comment]
@m0nac0 did you find some time to look at the open PRs?

**Comment by m0nac0** [comment]
@mindthefish Amazing work, I finally noticed the activity in this repo! I'm so sorry for missing it for such a long time. I merged your three PRs. We can still update the reference in the annotation extension, what else has to be done? 
(Sorry, I wanted to get back to your right away, I'll need to allocate some time to get back into the details of this project)

**Comment by mindthefish** [comment]
I am also just trying to get back into the project. 😆  
I think I got the example project to compile again. I'm not an expert in these topics either, but together I'm sure we'll get a good bit further. 👍

**Comment by m0nac0** [comment]
#9 is merged and this library should now work on iOS. 🎉 

Thank you @mindthefish !

Please open new issues if you find any bugs!
