### ISSUE TITLE
can anyone explain why have 2 files of pubspec.yaml what mean that which one i use

### ISSUE THREAD

**Issue by Yousef910** [maplibre/flutter-maplibre-gl#218]
I'm beginner in flutter I want to know how why their are 2 files of pubspec.yam and I must use the example folder for my project or  I must use the all folders in my project please  i want just simple explain0

**Comment by mariusvn** [comment]
the pubspec.yaml in the root folder is the library dependencies, and the pubspec.yaml in the example folder is the depenedencies of the example app

**Comment by mariusvn** [comment]
can you close the issue ? thanks in advence

**Comment by m0nac0** [comment]
Closing since the question has been answered.
